name: lab
channels: [conda-forge]
dependencies:
  - python=3.12
  - jupyterlab
  - ipywidgets
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - spacy
  - spacy-model-en_core_web_sm
  - transformers
  - datasets
  - accelerate
  - tokenizers
  - sentencepiece
  - pyarrow
  - psycopg2
  - requests
  - beautifulsoup4
